# Generated by Django 6.0.8 on 2026-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('pa', 'Punjabi')], default='hi', help_text='Preferred language for SMS notifications and UI', max_length=10),
        ),
    ]
